---
title: GitBash（MSYS2）でsshしたときの文字化けを解消する
published: 2020-07-19 05:06:58
tags: encoding
---

* はじめに

  タイトルまんまです。
  
  やんごとなき理由により、Linuxサーバ（RHEL7）でとあるユーザの文字エンコーディングをUTF-8からEUC-JPに変更する必要があった。
  ちゃんと ~ja_JP.eucjp~ もインストールされていたので、対象ユーザの ~~/.bash_profile~ に以下を設定すれば良い。

  #+BEGIN_SRC sh
  $ cat ~/.bash_profile | grep LANG
  LANG=ja_JP.eucjp
  #+END_SRC

  設定されているかの確認は以下（ ~source~ するか、再ログインしてから確認する） 。

  #+BEGIN_SRC sh
  $ env | grep "^LANG="
  LANG=ja_JP.eucjp
  #+END_SRC

  これでちゃんと日本語が表示されるはずなのだが、GitBashでsshして接続すると、何故か文字化けしてしまう。

#TEASER#  

* 原因

  まんまこれと同じでした。

  - [[https://ja.stackoverflow.com/questions/55304/msys2-%25E3%2581%25AE-ssh-%25E3%2581%25A7euc-jp%25E7%2592%25B0%25E5%25A2%2583%25E3%2581%25AB%25E3%2583%25AA%25E3%2583%25A2%25E3%2583%25BC%25E3%2583%2588%25E6%258E%25A5%25E7%25B6%259A%25E3%2581%2597%25E3%2581%259F%25E5%25A0%25B4%25E5%2590%2588%25E3%2581%25AB%25E6%2596%2587%25E5%25AD%2597%25E5%258C%2596%25E3%2581%2591%25E3%2582%2592%25E5%259B%259E%25E9%2581%25BF%25E3%2581%2599%25E3%2582%258B%25E6%2596%25B9%25E6%25B3%2595][msys2 の ssh でeuc-jp環境にリモート接続した場合に文字化けを回避する方法]]

  GitBash（Git for Windowsに同梱されているシェル環境）は[[https://qiita.com/Ted-HM/items/9a60f6fcf74bbd79a904#git-for-windows][MSYS2ベース]]なので、同じ現象に該当すると思われる。
  状況としては、サーバからEUC-JPエンコーディングのバイナリが送られているが、クライアント側で別のエンコーディングのデータとして解釈されており、結果として文字化けが発生しているようだ。
  

* 解決

  同じページの回答にある、 ~luit~ というツールを導入することで解消した。このツールは、プロセスの間に立って受け取るデータのエンコーディングをいい感じに変換してくれるみたい。
  ~luit.exe~ のバイナリをパスの通ったディレクトリに起き、以下を実行すれば文字化けなく表示される。

  #+BEGIN_SRC sh
  luit.exe -encoding eucjp -- ssh ${SERVERNAME}
  #+END_SRC

  毎回これをするのはめんどいが、そんなに実行する機会もないはずなので、一旦はこれでOK。
  （当初はサーバ側の問題と勘違いし、設定方法を確認したり[[https://qiita.com/qiitamatumoto/items/efffc0ef6e6249533201][このあたり]]やってみたりで半日くらい時間を溶かしてしまったのは秘密。）

** ちなみに
   同様にクライアントが受け取る文字エンコーディングをいい感じに変換してくれるツールとして、 [[https://qiita.com/Ted-HM/items/9a60f6fcf74bbd79a904#cocot][cocot]]というのもある。
   最初自分もこちらを試してみたが、うまく動かせなかった（多分使い方が間違ってる）。
  
* 補記
  Windowsで使えるシェル環境ってあんまり知らなかったけど、調べている中で面白い記事を発見した。
  
  - [[https://qiita.com/Ted-HM/items/9a60f6fcf74bbd79a904][Windowsで使えるターミナルとシェルのまとめ]]

    
  結構いろんなシェル環境があるんだなー。普段はGitBash（か、たまにCygwin）しか使ってないけど、ちょっと他のも使ってみようかな。
