---
title: Intellij Ideaの設定ことはじめ
published: 2021-01-22 17:10:24
updated: 2021-01-26 22:54:14
tags: Java, Intellij
---
#+OPTIONS: ^:{}
#+OPTIONS: \n:t

仕事でちょこちょこIntellij Ideaを使っているが、なかなかに使用頻度が少ないので、毎回どんな設定を入れればよいか忘れてしまう。
なので、メモっておこうと。

設定を変更したら、随時更新する。

@@html:<!--more-->@@

* 設定の共有

  https://pleiades.io/help/idea/sharing-your-ide-settings.html

  複数の端末にインストールしたIntellij Ideaの設定を共有できる。
  共有の方法には以下の方法がある。

  1. Settings Sync による同期 (Ultimateのみ)
  2. Settings Repository による同期
  3. 設定のエクスポート/インポート による同期


  Ultimateを購入すると1の方法が使えるが、異なるOS間ではキーマップが同期されないようなので、2の方法で実施する。
  参考: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000784770-IDE-Settings-Sync-not-synchronizing-keymap

  Settings Sync を無効にした上で、 ~File~ → ~Manage IDE Settings~ → ~Settings Repository~ より設定する。

  Build Settingなどは同期されないみたいなので、いくつかはマシンごとにポチポチする必要がありそう。


* キーマップ

** きほん
  - ~Ctrl + Alt + s~  :: 設定画面
  - ~Ctrl + Alt + Shift + S~  :: プロジェクト設定画面
  - ~Ctrl + Shift + Enter~  :: Complete Current Statement
  - ~Alt + Enter~  :: Show Context Action
  - ~Alt + Insert~  :: Generate... / New...

  - ~Alt + .~  :: Go To Declaration or Usages
  - ~Ctrl + U, Alt + .~  :: Go To Implementation(s)
  - ~Ctrl + Shift + B~  :: Type Declaration
  - ~Ctrl + Shift + T~  :: Test

  - ~Ctrl + F5~  :: Rerun

** 自分で追加したもの
   # - ~Ctrl + G~  :: Escape
   #   - Emacs+ Patchedでは keyboard-quit に割り当てられているが、うまく働かないので変更。
   - ~Ctrl + W~  :: Kill Selected Region (Editor Actions)
     - Emacs+ Patchedでは kill-region に割り当てられているが、うまく働かないので変更。
   - ~Ctrl + H~  :: BackSpace
     - Hierarchy に割り当てられているのを変更。
   - ~Ctrl + X, B~  :: Switcher
     - Emacs+ Patchedでは switch-to-buffer に割り当てられているが、うまく働かないので変更。
   - ~Alt + F11~  :: Maven
   - ~Ctrl + Shift + J~  :: Commit... (In Main Menu | Git)

* プラグイン

  設定画面左上の検索欄で「 ~plugin~ 」と入力するとプラグイン一覧が出てくるので、必要なものをインストールする。

** Japanese Language Pack
   - 日本語化用
   - そんなに使用しなくてもいいかも（英語のほうが情報多いので）

** Key Promoter X
   - キーバインドで実行できる操作をマウスでやっちゃうと、対応するキーバインドを教えてくれる
   - キーバインドが登録されていない操作をすると、キーバインド登録の提案をしてくれる

** Emacs+ Patched
   - Emacsキーマップの設定
   - https://qiita.com/crossroad0201/items/eecc87dd1c0258148167 あたりを参考に。

* JVM設定

  https://qiita.com/kazuki43zoo/items/49c90e5f05397c694d26 より。
  Intellij Ideaが使用するJVMの設定。

  ~Help~ → ~Edit Custom VM Options...~ を選択。

** ヒープサイズ
   ヒープサイズが、デフォルトでは700MBと少し心許ないため、以下設定を追加する。

   #+BEGIN_SRC 
   -Xms2048m
   -Xmx2048m
   #+END_SRC

* Mavenプロジェクトの設定

** Importing
   ソースコードやドキュメントは、自動的にダウンロードするようにする。

   設定画面から「 ~Build, Extension, Deployment~ → ~Build Tools~ → ~Maven~ → ~Importing~ 」を選択し
   （もしくは、設定画面左上の検索欄で「 ~Importing~ 」と入力し）、「 ~Automatically download~ 」の
   チェックボックスをすべてチェックしておく（ ~Sources~ 、 ~Documentation~ 、 ~Annotations~ ）。
