---
title: これからの勉強方針
published: 
updated: 
tags: personal
---
#+OPTIONS: ^:{}

最近仕事が忙しかったりで、なかなか勉強の習慣がついていないなー、と感じている
（休日は普通に休みなので、物理的に時間がないと言うわけではない。ないのだが、どうしても休息優先になっちゃうんだよなー、と）。

いろいろと興味のあるテーマはあるが、ちゃんとそれらを整理できていなかったりしてるので、
腰を据えて勉強しようと思う前に「何やるんだっけ？」で力尽きてしまったり、
調べものをしてるうちにいろんなところに興味が行ってしまって、「あれ、何勉強しようとしてたんだっけ？」という状態になってることが多い。

そして、休息が必要なことを理由にして、勉強をサボってるなー、モチベーションが上がらんなー、と感じることも多くなり、
ちょっとモヤモヤしていたところ、会社の尊敬する先輩であるkazuhiraさんのブログの記事を読んだ。

[[https://kazuhira-r.hatenablog.com/entry/2021/06/04/003342][ブログを書き始めてから、10年経ちました]]

自分が何に興味があるのか。やりたいことは何なのか。改めて、自分の中で整理してみる。

@@html:<!--more-->@@

** このブログについて

   自分の勉強したことや、試したことを書く場として開設しました。以前ははてなブログを使っていたのですが、なんとなく愛着がわかなくてGitHub Pagesへ移行しました。
   書くときの題材は、自分が試してみてうまく行かなかったことや、なかなか情報が見つからず苦労したことを選択することが多かった気がします。

   人に読んでもらおうと思って書くことは少ないのですが、それでも「どうせならあんまり情報がなさそうなことを書いたほうが価値が大きいかな」と書く題材は選んでいたと思います。
   しかし、「その時苦労してなんとか解決したこと」をあとから読み返すことってそんなになかったです（もう解決していることだから）。

   もともと書くこと自体を目的としてはいなかったですし、自分が後で見返して役に立つといいなという思惑も込めて、
   今後は情報の多寡にかかわらず書いていこうと思います。

   #+begin_quote
   基本的には自分の勉強のため、未来の自分が見て読み返して、思い出せるために書いています。
   1回ちゃんと書いておけば、あとで見ても書いた当時にどういうことをやったのか、意外と思い出せるものだったりします。
   #+end_quote
